export const LANG = {
  tr: {
    tagline:"cursor forgets. sovereign remembers.",
    placeholder:"Stripe entegrasyonu ekle, auth middleware güncelle...",
    inputLabel:"NE YAPMAK İSTİYORSUN?",
    analyzeBtn:"Analiz Et & Kontrol Et",
    analyzing:"Analiz ediliyor",
    approve:"Onayla", reject:"Reddet",
    whyBtn:"? Neden bu skor", whyClose:"▲ Kapat",
    riskBreak:"RİSK DÖKÜMÜ",
    approved:"ONAYLANDI", rejected:"REDDEDİLDİ",
    decisionFlow:"KARAR AKIŞI",
    passed:"geçti", session:"OTURUM",
    total:"Toplam", auto:"Otomatik",
    approvedStat:"Onaylanan", rejectedStat:"Reddedilen",
    empty:"Bekleyen karar yok.", pending:"ONAY GEREKİYOR",
    nav:["İstem","Gösterge","Kararlar","Ayarlar"],
    factors:["Güvenlik sorunları","Var olmayan paket/API","Bağımlılık riski","Etkilenen alan","MCP izin riski","Git etkisi"],
    safe:"güvenli", pendingChip:"onay bekliyor", blocked:"durduruldu",
    recentChanges:"Son Değişiklikler",
    emptyDash:"Henüz karar yok.", emptyDashSub:"Bir prompt girerek başla.",
    goPrompt:"Prompt'a Git",
    filterAll:"Hepsi", filterApproved:"Onaylanan", filterRejected:"Reddedilen", filterPending:"Bekleyen",
    emptyDec:"Bu filtrede karar yok.",
    noDecisions:"Henüz karar verilmedi.", noDecisionsSub:"Analizler burada listelenir.",
    settingsLang:"Dil", settingsRisk:"Risk Eşiği",
    settingsRiskNote:"Bu değerin üzerindeki skorlar insan onayı gerektirir.",
    settingsClear:"Tüm Verileri Temizle",
    settingsClearNote:"Kararlar ve oturum istatistikleri sıfırlanır.",
    settingsClearBtn:"Temizle",
    settingsVersion:"Sürüm",
  },
  en: {
    tagline:"cursor forgets. sovereign remembers.",
    placeholder:"Add Stripe integration, update auth middleware...",
    inputLabel:"WHAT DO YOU WANT TO DO?",
    analyzeBtn:"Analyze & Check",
    analyzing:"Analyzing",
    approve:"Approve", reject:"Reject",
    whyBtn:"? Why this score", whyClose:"▲ Close",
    riskBreak:"RISK BREAKDOWN",
    approved:"APPROVED", rejected:"REJECTED",
    decisionFlow:"DECISION FLOW",
    passed:"passed", session:"SESSION",
    total:"Total", auto:"Automatic",
    approvedStat:"Approved", rejectedStat:"Rejected",
    empty:"No pending decisions.", pending:"APPROVAL NEEDED",
    nav:["Prompt","Dashboard","Decisions","Settings"],
    factors:["Security issues","Non-existent package/API","Dependency risk","Affected area","MCP permission risk","Git impact"],
    safe:"safe", pendingChip:"pending approval", blocked:"blocked",
    recentChanges:"Recent Changes",
    emptyDash:"No decisions yet.", emptyDashSub:"Enter a prompt to get started.",
    goPrompt:"Go to Prompt",
    filterAll:"All", filterApproved:"Approved", filterRejected:"Rejected", filterPending:"Pending",
    emptyDec:"No decisions in this filter.",
    noDecisions:"No decisions yet.", noDecisionsSub:"Analyses will be listed here.",
    settingsLang:"Language", settingsRisk:"Risk Threshold",
    settingsRiskNote:"Scores above this value require human approval.",
    settingsClear:"Clear All Data",
    settingsClearNote:"Decisions and session stats will be reset.",
    settingsClearBtn:"Clear",
    settingsVersion:"Version",
  },
};
